---
title: "[AC-1496] Genymotion causing Android SDK not to load."
---
<table>
<tr><th>Type</th><td>Bug</td></tr>
<tr><th>Priority</th><td>n/a</td></tr>
<tr><th>Status</th><td>Resolved</td></tr>
<tr><th>Resolution</th><td>Duplicate</td></tr>
<tr><th>Resolution Date</th><td>2014-07-28T19:07:57.000+0000</td></tr>
<tr><th>Affected Version/s</th><td>n/a</td></tr>
<tr><th>Fix Version/s</th><td>n/a</td></tr>
<tr><th>Components</th><td>Studio</td></tr>
<tr><th>Labels</th><td>3.3.0.GA, android, genymotion</td></tr>
<tr><th>Reporter</th><td>Paul Flood</td></tr>
<tr><th>Assignee</th><td>Chris Barber</td></tr>
<tr><th>Created</th><td>2014-07-22T05:03:49.000+0000</td></tr>
<tr><th>Updated</th><td>2016-03-08T07:37:56.000+0000</td></tr>
</table>

<h3>Description</h3>

I updated Titanium with latest updates so Studio and the SDK are at 3.3.0. As soon as this happened I got the following error.

[Android SDK Home] No Android SDKs were found under the specified SDK location

After doing a bit of searching I found this article.

<a href="https://developer.appcelerator.com/question/176318/alternative-solution-android-sdk-home-no-android-sdks-were-found-under-the-specified-sdk-location" rel="nofollow" target="_blank">https://developer.appcelerator.com/question/176318/alternative-solution-android-sdk-home-no-android-sdks-were-found-under-the-specified-sdk-location</a>

I tried removing the genymotion.js file from all the SDK version that contained it but I still received the SDK error. On running 'ti info' with the file removed I got the following:

<code><pre>
 |[ERROR] Failed to run command "info"
[ERROR] Error: Cannot find module 'titanium-sdk/lib/emulators/genymotion'
    at Module._resolveFilename (module.js:338:15)
    at Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/paul/Library/Application Support/Titanium/mobilesdk/osx/3.3.0.GA/cli/lib/genymotion.js:5:15)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
---------------------------------------------
    at Object.run (/usr/local/lib/node_modules/titanium/node_modules/node-appc/lib/subprocess.js:59:8)
    at find (/usr/local/lib/node_modules/titanium/node_modules/node-appc/lib/subprocess.js:96:14)
    at q.process (/usr/local/lib/node_modules/titanium/node_modules/async/lib/async.js:731:21)
    at processImmediate (timers.js:330:15)
</pre></code>

By turning off Genymotion in Titianium using the following command 'ti config genymotion.enabled false' the error disappeared and I could build my app to a device or using AVD.

I would like to use Genymotion, when it is enabled and the genymotion.js file has been returned to the SDK folder I get the following error when running 'ti info'.

<code><pre>
/usr/local/lib/node_modules/titanium/node_modules/longjohn/dist/longjohn.js:185
        throw e;
              ^
Error: Callback was already called.
    at /Users/paul/Library/Application Support/Titanium/mobilesdk/osx/3.3.0.GA/node_modules/async/lib/async.js:22:31
    at /Users/paul/Library/Application Support/Titanium/mobilesdk/osx/3.3.0.GA/node_modules/async/lib/async.js:229:17
    at /Users/paul/Library/Application Support/Titanium/mobilesdk/osx/3.3.0.GA/node_modules/async/lib/async.js:516:34
    at /Users/paul/Library/Application Support/Titanium/mobilesdk/osx/3.3.0.GA/node_modules/titanium-sdk/lib/emulators/genymotion.js:370:8
    at conn.exec.bufferUntilClose (/Users/paul/Library/Application Support/Titanium/mobilesdk/osx/3.3.0.GA/node_modules/titanium-sdk/lib/adb.js:483:5)
    at Connection.<anonymous> (/Users/paul/Library/Application Support/Titanium/mobilesdk/osx/3.3.0.GA/node_modules/titanium-sdk/lib/adb.js:257:11)
    at EventEmitter.emit (events.js:95:17)
    at writeAfterEnd (_stream_writable.js:132:10)
    at Writable.write (_stream_writable.js:178:5)
---------------------------------------------
    at Connection.exec (/Users/paul/Library/Application Support/Titanium/mobilesdk/osx/3.3.0.GA/node_modules/titanium-sdk/lib/adb.js:253:9)
    at ADB.<anonymous> (/Users/paul/Library/Application Support/Titanium/mobilesdk/osx/3.3.0.GA/node_modules/titanium-sdk/lib/adb.js:482:9)
    at Connection.<anonymous> (/Users/paul/Library/Application Support/Titanium/mobilesdk/osx/3.3.0.GA/node_modules/titanium-sdk/lib/adb.js:247:4)
    at EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:910:16
    at process._tickCallback (node.js:415:13)
</pre></code>

I hope you can figure this out.

<h3>Comments</h3>

<ol>
<li>Simon Buckingham 2014-07-23

   I have exactly the same problem. And what is more when doing automatic updates from Ti Studio 3.2.3 (to Ti 3.3) it goes through the process and then i find by running ti -v or alloy -v that the version has not been updated and so I have to do it manually with npm.
   Cheers Simon Buckingham</li>
<li>Paul Flood 2014-07-24

   I've resolved this, the old virtual device images were causing the errors above. After deleting the Genymotion virtual devices and installing a new one the error disappeared. The virtual devices were version 1.0 and Genymotion was version 2.2. This worked fine before I updated to 3.3.0 but after the virtual devices needed to updated.
   
   </li>
<li>Bert Grantges 2014-07-26

   I can confirm that I was having the same issue as described above - removing all 1.0 version emulaters fixed my issue as well.
   </li>
<li>Chris Barber 2014-07-28

   Dupe of TIMOB-17344.</li>
</ol>


<p><a href="/AC/AC-1496.json">JSON Source</a></p>