{
	"id": "136381",
	"key": "AC-1487",
	"fields": {
		"issuetype": {
			"id": "1",
			"description": "A problem which impairs or prevents the functions of the product.",
			"name": "Bug",
			"subtask": false
		},
		"project": {
			"id": "12217",
			"key": "AC",
			"name": "Appcelerator - INBOX",
			"projectCategory": {
				"id": "10000",
				"description": "",
				"name": "Customer Service"
			}
		},
		"resolution": {
			"id": "5",
			"description": "All attempts at reproducing this issue failed, or not enough information was available to reproduce the issue. Reading the code produces no clues as to why this behavior would occur. If more information appears later, please reopen the issue.",
			"name": "Cannot Reproduce"
		},
		"resolutiondate": "2015-02-03T15:16:09.000+0000",
		"created": "2014-09-10T16:50:59.000+0000",
		"labels": [
			"TCSupportTriage",
			"crash",
			"ios",
			"iphone"
		],
		"versions": [],
		"issuelinks": [],
		"assignee": {
			"name": "mpmiranda",
			"key": "mpmiranda",
			"displayName": "Mauro Parra-Miranda",
			"active": true,
			"timeZone": "America/Mexico_City"
		},
		"updated": "2016-03-08T07:37:56.000+0000",
		"status": {
			"description": "The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.",
			"name": "Closed",
			"id": "6",
			"statusCategory": {
				"id": 3,
				"key": "done",
				"colorName": "green",
				"name": "Done"
			}
		},
		"components": [
			{
				"id": "14548",
				"name": "Titanium SDK & CLI",
				"description": "Please enter tickets related to the MobileSDK here."
			}
		],
		"description": "We have a recurring error and we cannot reproduce this bug,\r\n90% of errors coming from Crashlytics are this one for iOS platform  :\r\n {quote}\r\nTiBase.m line 279\r\n__destroy_helper_block_187\r\nCrashed: com.apple.main-thread\r\nEXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0xc0000010\r\n0 libobjc.A.dylib 0x3b2ca7ea objc_release + 9\r\n1 libsystem_blocks.dylib 0x3b7f2ac5 _Block_release + 216\r\n2 MyApp 0x000dd697 __destroy_helper_block_187 (TiBase.m:279)\r\n3 libsystem_blocks.dylib 0x3b7f2ac5 _Block_release + 216\r\n4 MyApp 0x000dd839 TiThreadProcessPendingMainThreadBlocks (TiBase.m:366)\r\n {quote}\r\n\r\nTo fix this error we change TiBase.m and TiThreadProcessPendingMainThreadBlocks method\r\nhttps://github.com/appcelerator/titanium_mobile/pull/6045 : \r\nWe use autorelease for \"thisAction\" and we replace NSAutoreleasePool with new syntax : @autoreleasepool.\r\n\r\nDo you think this fix is appropriate?\r\n\r\nThanks for your help",
		"attachment": [],
		"flagged": false,
		"summary": " crash TiBase : TiThreadProcessPendingMainThreadBlocks",
		"creator": {
			"name": "hangeul",
			"key": "hangeul",
			"displayName": "Jonathan ",
			"active": true,
			"timeZone": "Europe/Berlin"
		},
		"subtasks": [],
		"reporter": {
			"name": "hangeul",
			"key": "hangeul",
			"displayName": "Jonathan ",
			"active": true,
			"timeZone": "Europe/Berlin"
		},
		"environment": "Ti SDK - 3.3.0.GA\r\nTi CLI - v3.3.0\r\n",
		"comment": {
			"comments": [
				{
					"id": "322905",
					"author": {
						"name": "mpmiranda",
						"key": "mpmiranda",
						"displayName": "Mauro Parra-Miranda",
						"active": true,
						"timeZone": "America/Mexico_City"
					},
					"body": "Hello,\r\ndo you have any code that can reproduces it? How large is your installation and how many crashes do you have? \r\n\r\nBest Regards!",
					"updateAuthor": {
						"name": "mpmiranda",
						"key": "mpmiranda",
						"displayName": "Mauro Parra-Miranda",
						"active": true,
						"timeZone": "America/Mexico_City"
					},
					"created": "2014-09-10T20:38:01.000+0000",
					"updated": "2014-09-10T20:38:01.000+0000"
				},
				{
					"id": "323039",
					"author": {
						"name": "hangeul",
						"key": "hangeul",
						"displayName": "Jonathan ",
						"active": true,
						"timeZone": "Europe/Berlin"
					},
					"body": "Hello and thanks for your help.\r\nWe cannot reproduce this bug but this error is level 1 on Crashlytics : \r\n1330 crashes for 994 users\r\nOur fix doesn't work (https://github.com/appcelerator/titanium_mobile/pull/6045) because we have a new crash with the same error.",
					"updateAuthor": {
						"name": "hangeul",
						"key": "hangeul",
						"displayName": "Jonathan ",
						"active": true,
						"timeZone": "Europe/Berlin"
					},
					"created": "2014-09-11T10:13:09.000+0000",
					"updated": "2014-09-11T10:13:09.000+0000"
				},
				{
					"id": "341831",
					"author": {
						"name": "mpmiranda",
						"key": "mpmiranda",
						"displayName": "Mauro Parra-Miranda",
						"active": true,
						"timeZone": "America/Mexico_City"
					},
					"body": "We haven't seen this. If you are able to come up with a testcase that reproduces the issue, we can reopen this one. ",
					"updateAuthor": {
						"name": "mpmiranda",
						"key": "mpmiranda",
						"displayName": "Mauro Parra-Miranda",
						"active": true,
						"timeZone": "America/Mexico_City"
					},
					"created": "2015-02-03T15:16:09.000+0000",
					"updated": "2015-02-03T15:16:09.000+0000"
				}
			],
			"maxResults": 3,
			"total": 3,
			"startAt": 0
		}
	}
}