{
	"id": "173472",
	"key": "AC-6211",
	"fields": {
		"issuetype": {
			"id": "1",
			"description": "A problem which impairs or prevents the functions of the product.",
			"name": "Bug",
			"subtask": false
		},
		"project": {
			"id": "12217",
			"key": "AC",
			"name": "Appcelerator - INBOX",
			"projectCategory": {
				"id": "10000",
				"description": "",
				"name": "Customer Service"
			}
		},
		"resolution": {
			"id": "11",
			"description": "Is not a bug in our product",
			"name": "Not Our Bug"
		},
		"resolutiondate": "2019-04-22T22:31:45.000+0000",
		"created": "2019-04-16T11:22:06.000+0000",
		"labels": [
			"android"
		],
		"versions": [],
		"issuelinks": [],
		"assignee": {
			"name": "shossain",
			"key": "shossain",
			"displayName": "Shak Hossain",
			"active": false,
			"timeZone": "America/Los_Angeles"
		},
		"updated": "2019-04-22T22:31:45.000+0000",
		"status": {
			"description": "A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.",
			"name": "Resolved",
			"id": "5",
			"statusCategory": {
				"id": 3,
				"key": "done",
				"colorName": "green",
				"name": "Done"
			}
		},
		"components": [],
		"description": "{code:java}\r\nERROR] :  TiExceptionHandler: (main) [1594,8795] /app.js:375\r\n\r\n[ERROR] :  TiExceptionHandler:       FirebaseAnalytics.log(’test’);\r\n\r\n[ERROR] :  TiExceptionHandler:                         ^\r\n\r\n[ERROR] :  TiExceptionHandler: Error: Failed resolution of: Lcom/google/android/gms/measurement/internal/zzbw;\r\n\r\n[ERROR] :  TiExceptionHandler:     at Object.callback (/app.js:375:25)\r\n\r\n[ERROR] :  TiExceptionHandler:     at TableViewRow.<anonymous> (/ui/templates/menu.js:121:7)\r\n\r\n[ERROR] :  TiExceptionHandler:     at TableViewRow.value (ti:/events.js:50:21)\r\n\r\n[ERROR] :  TiExceptionHandler:     at TableViewRow.value (ti:/events.js:102:19)\r\n\r\n[ERROR] :  TiExceptionHandler:\r\n\r\n[ERROR] :  TiExceptionHandler:     com.google.firebase.analytics.FirebaseAnalytics.getInstance(Unknown Source)\r\n\r\n[ERROR] :  TiExceptionHandler:     firebase.analytics.TitaniumFirebaseAnalyticsModule.analyticsInstance(TitaniumFirebaseAnalyticsModule.java:37)\r\n\r\n[ERROR] :  TiExceptionHandler:     firebase.analytics.TitaniumFirebaseAnalyticsModule.log(TitaniumFirebaseAnalyticsModule.java:46)\r\n\r\n[ERROR] :  TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)\r\n\r\n[ERROR] :  TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:63)\r\n\r\n[ERROR] :  TiExceptionHandler:     org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:978)\r\n\r\n[ERROR] :  TiExceptionHandler:     org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1207)\r\n\r\n[ERROR] :  TiExceptionHandler:     org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:265)\r\n\r\n[ERROR] :  TiExceptionHandler:     ti.modules.titanium.ui.TableViewRowProxy.handleMessage(TableViewRowProxy.java:210)\r\n\r\n[ERROR] :  TiExceptionHandler:     android.os.Handler.dispatchMessage(Handler.java:98)\r\n\r\n[ERROR] :  V8Exception: Exception occurred at /app.js:375: Uncaught Error: Failed resolution of: Lcom/google/android/gms/measurement/internal/zzbw;\r\n\r\n[ERROR] :  EGL_emulation: tid 3521: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)\r\n{code}\r\n",
		"attachment": [],
		"flagged": false,
		"summary": "At titanium-firebase-analytics (Android 3.0.0) i have found the following bug:",
		"creator": {
			"name": "andreas.pingas",
			"key": "andreas.pingas",
			"displayName": "Andreas Pingas",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"subtasks": [],
		"reporter": {
			"name": "andreas.pingas",
			"key": "andreas.pingas",
			"displayName": "Andreas Pingas",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"environment": null,
		"comment": {
			"comments": [
				{
					"id": "447812",
					"author": {
						"name": "andreas.pingas",
						"key": "andreas.pingas",
						"displayName": "Andreas Pingas",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"body": "https://github.com/hansemannn/titanium-firebase-analytics\r\n\r\n{code:java}\r\nvar PlayServices = require('ti.playservices');\r\n\r\nvar FirebaseCore = require('firebase.core');\r\n\r\nvar FirebaseAnalytics = require('firebase.analytics');\r\n\r\nvar FirebaseCloudMessaging = require('firebase.cloudmessaging');\r\n\r\nFirebaseCore.configure();\r\n\r\nFirebaseAnalytics.log('test');\r\n{code}\r\n\r\n{code:java}\r\n[ERROR] :  TiExceptionHandler: (main) [3,34] /app.js:13\r\n[ERROR] :  TiExceptionHandler: FirebaseAnalytics.log('test');\r\n[ERROR] :  TiExceptionHandler:                   ^\r\n[ERROR] :  TiExceptionHandler: Error: Failed resolution of: Lcom/google/android/gms/measurement/internal/zzbw;\r\n[ERROR] :  TiExceptionHandler:     at /app.js:13:19\r\n[ERROR] :  TiExceptionHandler:     at Module._runScript (ti:/module.js:610:9)\r\n[ERROR] :  TiExceptionHandler:     at Module.load (ti:/module.js:106:7)\r\n[ERROR] :  TiExceptionHandler:     at Module.loadJavascriptText (ti:/module.js:455:9)\r\n[ERROR] :  TiExceptionHandler:     at Module.loadAsFile (ti:/module.js:510:15)\r\n[ERROR] :  TiExceptionHandler:     at Module.loadAsFileOrDirectory (ti:/module.js:427:20)\r\n[ERROR] :  TiExceptionHandler:     at Module.require (ti:/module.js:254:17)\r\n[ERROR] :  TiExceptionHandler:     at Module.global.Module.require (/ti.internal/extensions/binding.js:33:34)\r\n[ERROR] :  TiExceptionHandler:     at require (ti:/module.js:568:15)\r\n[ERROR] :  TiExceptionHandler:     at global.require (/ti.internal/extensions/binding.js:21:10)\r\n[ERROR] :  TiExceptionHandler:\r\n[ERROR] :  TiExceptionHandler:     com.google.firebase.analytics.FirebaseAnalytics.getInstance(Unknown Source)\r\n[ERROR] :  TiExceptionHandler:     firebase.analytics.TitaniumFirebaseAnalyticsModule.analyticsInstance(TitaniumFirebaseAnalyticsModule.java:37)\r\n[ERROR] :  TiExceptionHandler:     firebase.analytics.TitaniumFirebaseAnalyticsModule.log(TitaniumFirebaseAnalyticsModule.java:46)\r\n[ERROR] :  TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(Native Method)\r\n[ERROR] :  TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(V8Runtime.java:162)\r\n[ERROR] :  TiExceptionHandler:     org.appcelerator.kroll.KrollRuntime.runModule(KrollRuntime.java:207)\r\n[ERROR] :  TiExceptionHandler:     org.appcelerator.titanium.TiLaunchActivity.loadScript(TiLaunchActivity.java:99)\r\n[ERROR] :  TiExceptionHandler:     org.appcelerator.titanium.TiRootActivity.loadScript(TiRootActivity.java:414)\r\n[ERROR] :  TiExceptionHandler:     org.appcelerator.titanium.TiLaunchActivity.onResume(TiLaunchActivity.java:183)\r\n[ERROR] :  TiExceptionHandler:     org.appcelerator.titanium.TiRootActivity.onResume(TiRootActivity.java:432)\r\n{code}",
					"updateAuthor": {
						"name": "andreas.pingas",
						"key": "andreas.pingas",
						"displayName": "Andreas Pingas",
						"active": true,
						"timeZone": "America/Los_Angeles"
					},
					"created": "2019-04-20T14:00:55.000+0000",
					"updated": "2019-04-20T14:00:55.000+0000"
				},
				{
					"id": "447847",
					"author": {
						"name": "sdarda",
						"key": "sdarda",
						"displayName": "Sharif AbuDarda",
						"active": false,
						"timeZone": "Asia/Dhaka"
					},
					"body": "Hello [~andreas.pingas], This seems to be issue with the third party module used in the app. I would recommend contacting their support. Thanks.",
					"updateAuthor": {
						"name": "sdarda",
						"key": "sdarda",
						"displayName": "Sharif AbuDarda",
						"active": false,
						"timeZone": "Asia/Dhaka"
					},
					"created": "2019-04-22T22:31:20.000+0000",
					"updated": "2019-04-22T22:31:20.000+0000"
				}
			],
			"maxResults": 4,
			"total": 4,
			"startAt": 0
		}
	}
}