---
title: "[TIMOB-15734] Anvil: database test: testDatabaseExceptions fails"
---
<table>
<tr><th>Type</th><td>Bug</td></tr>
<tr><th>Priority</th><td>High</td></tr>
<tr><th>Status</th><td>Closed</td></tr>
<tr><th>Resolution</th><td>Fixed</td></tr>
<tr><th>Resolution Date</th><td>2013-11-16T18:45:43.000+0000</td></tr>
<tr><th>Affected Version/s</th><td>Release 3.2.0</td></tr>
<tr><th>Fix Version/s</th><td>2013 Sprint 23, 2013 Sprint 23 Core, Release 3.2.0</td></tr>
<tr><th>Components</th><td>Android, Anvil</td></tr>
<tr><th>Labels</th><td>n/a</td></tr>
<tr><th>Reporter</th><td>Allen Yeung</td></tr>
<tr><th>Assignee</th><td>Allen Yeung</td></tr>
<tr><th>Created</th><td>2013-11-16T09:11:33.000+0000</td></tr>
<tr><th>Updated</th><td>2013-12-18T02:08:01.000+0000</td></tr>
</table>

<h3>Description</h3>

The testDatabaseExceptions test case fails under the database suite in anvil.

To test, just run the database suite in anvil:
<code><pre>
node driver.js --mode=local --platform=android
</pre></code>

Then.. 
<code><pre>
CLI> start --config=default --suite=database
</pre></code>

<h3>Comments</h3>

<ol>
<li>Allen Yeung 2013-11-16

   <a href="https://github.com/appcelerator/titanium_mobile/pull/4986" rel="nofollow" target="_blank">https://github.com/appcelerator/titanium_mobile/pull/4986</a></li>
<li>Lokesh Choudhary 2013-12-18

   Verified the fix by running the database anvil test & the "testDatabaseExceptions" test was successful.
   
   Environment:
   Appcel Studio : 3.2.0.201312162210
   Ti SDK : 3.2.0.v20131216191854
   Mac OSX : 10.8.5
   Alloy : 1.3.0-cr2	
   CLI - 3.2.0-cr3
   Nexus 5 - android 4.4</li>
</ol>


<p><a href="/TIMOB/TIMOB-15734.json">JSON Source</a></p>