{
	"id": "160360",
	"key": "AC-3639",
	"fields": {
		"issuetype": {
			"id": "1",
			"description": "A problem which impairs or prevents the functions of the product.",
			"name": "Bug",
			"subtask": false
		},
		"project": {
			"id": "12217",
			"key": "AC",
			"name": "Appcelerator - INBOX",
			"projectCategory": {
				"id": "10000",
				"description": "",
				"name": "Customer Service"
			}
		},
		"resolution": {
			"id": "8",
			"description": "",
			"name": "Needs more info"
		},
		"resolutiondate": "2016-05-24T21:31:36.000+0000",
		"created": "2016-05-19T14:54:37.000+0000",
		"labels": [],
		"versions": [
			{
				"id": "17038",
				"name": "Appcelerator Studio 4.5.0",
				"archived": false,
				"released": false
			}
		],
		"issuelinks": [],
		"assignee": {
			"name": "shossain",
			"key": "shossain",
			"displayName": "Shak Hossain",
			"active": false,
			"timeZone": "America/Los_Angeles"
		},
		"updated": "2016-05-24T21:31:36.000+0000",
		"status": {
			"description": "The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.",
			"name": "Closed",
			"id": "6",
			"statusCategory": {
				"id": 3,
				"key": "done",
				"colorName": "green",
				"name": "Done"
			}
		},
		"components": [],
		"description": "h3. Steps to Reproduce\n- Go into my project directory\n- With the Titanium CLI : ti build -p ios -l 9.2 --log-level debug\n\nh3. Actual Result\nAfter the 'Launching iOS Simulator' line, a 'TypeError: Bad argument' exception is thrown.\nI could build and run without any problem a few weeks ago. Since I have not made any modification into my code and I cannot run anymore.\n\nh3. Expected Result\nI was expecting the same behaviour that a few weeks ago, that my app launches",
		"attachment": [
			{
				"id": "59314",
				"filename": ".log",
				"author": {
					"name": "greenhat",
					"key": "greenhat",
					"displayName": "Valentin AMATHIEU",
					"active": true,
					"timeZone": "America/Los_Angeles"
				},
				"created": "2016-05-19T14:54:46.000+0000",
				"size": 6759662,
				"mimeType": "text/plain"
			},
			{
				"id": "59315",
				"filename": "build_iphone.log",
				"author": {
					"name": "greenhat",
					"key": "greenhat",
					"displayName": "Valentin AMATHIEU",
					"active": true,
					"timeZone": "America/Los_Angeles"
				},
				"created": "2016-05-19T14:54:49.000+0000",
				"size": 120926,
				"mimeType": "text/plain"
			}
		],
		"flagged": false,
		"summary": "My titanium ios project seems to build but throw an exception when launches ios simulator (ipad)",
		"creator": {
			"name": "greenhat",
			"key": "greenhat",
			"displayName": "Valentin AMATHIEU",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"subtasks": [],
		"reporter": {
			"name": "greenhat",
			"key": "greenhat",
			"displayName": "Valentin AMATHIEU",
			"active": true,
			"timeZone": "America/Los_Angeles"
		},
		"environment": null,
		"comment": {
			"comments": [
				{
					"id": "386237",
					"author": {
						"name": "sdarda",
						"key": "sdarda",
						"displayName": "Sharif AbuDarda",
						"active": false,
						"timeZone": "Asia/Dhaka"
					},
					"body": "Hello,\r\n\r\nAs you are using Appcelerator studio and I presume you have Appcelerator installed correctly, I would suggest you run the app with \"appc run -p ios -l 9.2\". \r\n\r\nNow, If that didn't work I would suggest you run \r\n\"appc use latest\"\r\n\"appc setup\"\r\n\r\nIf this commands runs successfully, then there is no problem with your environment.  \r\n\r\nRegards,\r\nSharif.\r\n",
					"updateAuthor": {
						"name": "sdarda",
						"key": "sdarda",
						"displayName": "Sharif AbuDarda",
						"active": false,
						"timeZone": "Asia/Dhaka"
					},
					"created": "2016-05-19T18:25:31.000+0000",
					"updated": "2016-05-19T18:25:31.000+0000"
				}
			],
			"maxResults": 1,
			"total": 1,
			"startAt": 0
		}
	}
}